# Listener local non-TLS — vNode communique en intra-réseau Docker
listener 1883
allow_anonymous true

# Logs
log_type error
log_type warning
log_type notice
log_dest file /mosquitto/log/mosquitto.log
persistence true
persistence_location /mosquitto/data/
